### ISSUE TITLE
Requires manual installation...

### ISSUE THREAD

**Issue by jimscard** [technovangelist/ollamamodelupdater#3]
It's a lot easier to install and maintain utilities like this on macOS if it's integrated with a package manager, such as homebrew. 

So, I've added a Cask that installs the latest version to my tap. To use, at a macOS terminal prompt:

```
brew tap jimscard/ollama
brew install jimscard/ollama/ollama-model-updater
```

**Comment by robinmordasiewicz** [comment]
I tried the commands on my M1 Mac, and ran updater after brew installed it and everything worked as expected, except the binary name is without the dashes in the name, should the cask be named "jimscard/ollama/ollamamodelupdater" ?
The binary gets installed without an "r" at the end of the binary name like so
/opt/homebrew/bin/ollamamodelupdate
This would be useful information in the README.md

**Comment by jimscard** [comment]
> I tried the commands on my M1 Mac, and ran updater after brew installed it and everything worked as expected, except the binary name is without the dashes in the name, should the cask be named "jimscard/ollama/ollamamodelupdater" ? The binary gets installed without an "r" at the end of the binary name like so /opt/homebrew/bin/ollamamodelupdate This would be useful information in the README.md

When I made the cask, I tried to maintain the original name & binary name, e.g., this repository is "ollamamodelupdater" with the r, but the binary releases are "ollamamodelupdate" (no r), in addition to a bit more standard format, e.g., ollama-model-updater. 

I think I'll add the "r" versions as well (they're just symbolic links in /usr/local/bin anyway) ...
