### ISSUE TITLE
Running ollamamodelupdater triggers unidentified developer error...

### ISSUE THREAD

**Issue by jimscard** [technovangelist/ollamamodelupdater#4]
After installing ollamamodelupdater, running it in an iTerm2 window triggers an "unidentified developer" error requiring a [security exception](https://support.apple.com/guide/mac-help/open-a-mac-app-from-an-unidentified-developer-mh40616/mac) in order to be able to run it.

**Comment by technovangelist** [comment]
Correct. I don't pay Apple the 100 or 300 a year for the signing.
