### ISSUE TITLE
[BUG] Linux: only the loaded model is checked for updates

### ISSUE THREAD

**Issue by mann1x** [technovangelist/ollamamodelupdater#6]
Only the loaded model is cheked for updates on Linux, at least from the output:

ollama list output:
```shell
NAME                            ID              SIZE    MODIFIED
mistral-b-v0.2:latest           640f63ef63ed    5.1 GB  3 days ago
mistral-b-v0.2-Q4:latest        dc9a5bfa9e23    4.4 GB  3 days ago
tinyllama:latest                2644915ede35    637 MB  11 hours ago
```
ollamamodelupdate output:
```shell
You have the latest tinyllama:latest
```

**Comment by mann1x** [comment]
This happens if there are models manually imported from existing GGUF

**Comment by technovangelist** [comment]
Yup, makes sense. Nothing I can do if you are creating the model yourself

**Comment by mann1x** [comment]
The problem is that it stops updating the models as soon there's a model created from file
